### ISSUE TITLE
Hosten van website op git

### ISSUE THREAD

**Issue by MichielVL-BDP** [BDP-6IB/BDP-6IB.github.io#1]
Zet de website online met behulp van github pages.

Planning: succesvol online ten laatste 8 mei om 22u

Meer info: [GitHub Docs](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll)

**Comment by sanderbock** [comment]
Als je naar settings en dan naar pages navigeerd en op de visite site knop drukt word de website geopend
![Schermafbeelding 2023-05-08 192220](https://user-images.githubusercontent.com/132580114/236889602-10460271-9dc9-4b44-bfba-8864f7228c27.png)
